<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\WPF-Control\Source\Controls\H.Controls.Diagram.Presenter\H.Controls.Diagram.Presenter.csproj" />
    <ProjectReference Include="..\..\WPF-Control\Source\Extensions\H.Extensions.Behvaiors\H.Extensions.Behvaiors.csproj" />
  </ItemGroup>
</Project>