<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<Compile Remove="Assets\**" />
		<EmbeddedResource Remove="Assets\**" />
		<None Remove="Assets\**" />
		<Page Remove="Assets\**" />
		<Resource Remove="Assets\**" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\VisionMaster\WH.WisdomVisionPro.OpenCV\WH.WisdomVisionPro.OpenCV.csproj" />
	</ItemGroup>
</Project>